### ISSUE TITLE
Nginx Chef recipe can potentially throw NoMethodError during AMI provisioning

### ISSUE THREAD

**Issue by AndyJS** [datasift/datasift-connector#66]
Exception appears to rarely be an issue, but has been encountered whilst Packer provisions to t2.micro builder instance. This has not been observed since defaulting to t2.small instance_type in ami.json, but further investigation is needed.

```
Recipe: nginx::package
    amazon-ebs: * yum_package[nginx] action install
    amazon-ebs:
    amazon-ebs: ================================================================================
    amazon-ebs: Error executing action `install` on resource 'yum_package[nginx]'
    amazon-ebs: ================================================================================
    amazon-ebs:
    amazon-ebs: NoMethodError
    amazon-ebs: -------------
    amazon-ebs: undefined method `>' for nil:NilClass
    amazon-ebs:
    amazon-ebs: Resource Declaration:
    amazon-ebs: ---------------------
    amazon-ebs: # In /tmp/packer-chef-solo/cookbooks-0/nginx/recipes/package.rb
    amazon-ebs:
    amazon-ebs: 41: package node['nginx']['package_name'] do
    amazon-ebs: 42:   options package_install_opts
    amazon-ebs: 43:   notifies :reload, 'ohai[reload_nginx]', :immediately
    amazon-ebs: 44:   not_if 'which nginx'
    amazon-ebs: 45: end
    amazon-ebs: 46:
```
